# -*- coding: utf-8 -*-
"""board_games_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7lPAamz-MrYHUboDg4Of2iBI0JPGOxI
"""

"""
Telegram Bot for board game recommendations.
"""

import sys
if 'google.colab' in sys.modules:
    !pip install nest_asyncio
    !pip install python-telegram-bot --upgrade

import json
import pathlib
import re
import asyncio
from typing import List, Dict, Optional

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, ConversationHandler, ContextTypes

import nest_asyncio
nest_asyncio.apply()

GAMES_PATH = pathlib.Path("board_games_data/games_for_bot.json")
TOKEN = "8806853794:AAHePogJqD3nHNTZTHutHLsxxpG5Ra8yKB0"

PLAYERS, DURATION, AGE = range(3)


class BoardGameBot:
    """
    Main bot class for loading and filtering board games data.
    """

    def __init__(self):
        """Initialize bot and load games data from JSON file."""
        self.games = self.load_games()

    def load_games(self) -> List[Dict]:
        """
        Load board games data from JSON file.
        """
        if not GAMES_PATH.exists():
            print(f"File {GAMES_PATH} not found")
            return []

        with open(GAMES_PATH, 'r', encoding='utf-8') as f:
            games = json.load(f)
        print(f"Loaded {len(games)} games")
        return games

    def parse_players(self, players_str: str) -> Optional[tuple]:
        """
        Parse player count string into min and max players.
        """
        if not players_str:
            return None
        match = re.search(r'(\d+)\s*[-–]\s*(\d+)', str(players_str))
        if match:
            return (int(match.group(1)), int(match.group(2)))
        match = re.search(r'(\d+)', str(players_str))
        if match:
            num = int(match.group(1))
            return (num, num)
        return None

    def parse_duration(self, duration_str: str) -> Optional[int]:
        """
        Parse game duration from string.
        """
        if not duration_str:
            return None
        match = re.search(r'(\d+)', str(duration_str))
        if match:
            return int(match.group(1))
        return None

    def parse_age(self, age_str: str) -> Optional[int]:
        """
        Parse age restriction from string.
        """
        if not age_str:
            return None
        match = re.search(r'(\d+)\+', str(age_str))
        if match:
            return int(match.group(1))
        match = re.search(r'(\d+)', str(age_str))
        if match:
            return int(match.group(1))
        return None

    def check_age_match(self, game_age: Optional[int], user_age_category: int) -> bool:
        """
        Check if game age matches user age category.
        """
        if game_age is None:
            return True
        if user_age_category == 6:
            return 6 <= game_age <= 11
        elif user_age_category == 12:
            return 12 <= game_age <= 17
        elif user_age_category == 18:
            return game_age >= 18
        return True

    def filter_games(self, players_req: Optional[str], duration_req: Optional[str], age_req: Optional[str]) -> List[Dict]:
        """
        Filter games based on user requirements.
        """
        filtered = []
        players_num = None
        players_is_plus = False
        if players_req and players_req != 'skip':
            if players_req == '8+':
                players_num = 8
                players_is_plus = True
            else:
                players_num = int(players_req)
                players_is_plus = False

        duration_max = None
        if duration_req and duration_req != 'skip':
            duration_max = int(duration_req)

        age_category = None
        if age_req and age_req != 'skip':
            age_category = int(age_req.replace('+', ''))

        for game in self.games:
            if players_num:
                game_players = self.parse_players(game.get('players', ''))
                if game_players:
                    game_min, game_max = game_players
                    if players_is_plus:
                        if game_max < players_num:
                            continue
                    else:
                        if not (game_min <= players_num <= game_max):
                            continue
                else:
                    continue

            if duration_max:
                game_duration = self.parse_duration(game.get('duration', ''))
                if game_duration and game_duration > duration_max:
                    continue

            if age_category is not None:
                game_age = self.parse_age(game.get('age', ''))
                if not self.check_age_match(game_age, age_category):
                    continue

            filtered.append(game)

        return filtered

    def format_game_message(self, game: Dict, index: int, total: int) -> str:
        """
        Format game information for display.
        """
        description = game.get('description', '')
        return f"""
🎲 *[{index}/{total}]*

*{game['title']}*

👥 *Игроки:* {game['players'] if game['players'] else 'не указано'}
⏱ *Время:* {game['duration'] if game['duration'] else 'не указано'} мин
📅 *Возраст:* {game['age'] if game['age'] else 'не указано'}
🎭 *Жанр:* {game['genre'] if game['genre'] else 'не указано'}
💰 *Цена:* {game['price'] if game['price'] else 'не указано'} руб

📝 *Описание:*
{description}
"""


bot = BoardGameBot()


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle /start command. Initialize new search session.
    """
    context.user_data.clear()
    await update.message.reply_text(
        "🎲 *Добро пожаловать в бот подбора настольных игр!*\n\n"
        "Я помогу найти игру по вашим предпочтениям.",
        parse_mode='Markdown'
    )
    return await ask_players(update, context)


async def ask_players(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Ask user for number of players. Display inline keyboard with player options.
    """
    keyboard = [
        [InlineKeyboardButton("1", callback_data="players_1"),
         InlineKeyboardButton("2", callback_data="players_2"),
         InlineKeyboardButton("3", callback_data="players_3")],
        [InlineKeyboardButton("4", callback_data="players_4"),
         InlineKeyboardButton("5", callback_data="players_5"),
         InlineKeyboardButton("6", callback_data="players_6")],
        [InlineKeyboardButton("7", callback_data="players_7"),
         InlineKeyboardButton("8+", callback_data="players_8+")],
        [InlineKeyboardButton("🎲 Не важно", callback_data="players_skip")],
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    if update.callback_query:
        await update.callback_query.edit_message_text(
            "👥 *Сколько человек будет играть?*",
            reply_markup=reply_markup,
            parse_mode='Markdown'
        )
        return PLAYERS
    else:
        await update.message.reply_text(
            "👥 *Сколько человек будет играть?*",
            reply_markup=reply_markup,
            parse_mode='Markdown'
        )
        return PLAYERS


async def players_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle player count selection. Store choice and proceed to duration question.
    """
    query = update.callback_query
    await query.answer()
    data = query.data

    if data == "players_skip":
        context.user_data['players'] = None
    else:
        context.user_data['players'] = data.split('_')[1]

    keyboard = [
        [InlineKeyboardButton("⏱️ До 30 мин", callback_data="duration_30"),
         InlineKeyboardButton("⏱️ До 1 часа", callback_data="duration_60")],
        [InlineKeyboardButton("⏱️ До 2 часов", callback_data="duration_120"),
         InlineKeyboardButton("🎲 Не важно", callback_data="duration_skip")],
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    players_text = context.user_data.get('players', 'любое')
    await query.edit_message_text(
        f"👥 Игроков: *{players_text}*\n\n⏱️ *Сколько времени у вас есть?*",
        reply_markup=reply_markup,
        parse_mode='Markdown'
    )
    return DURATION


async def duration_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle duration selection. Store choice and proceed to age question.
    """
    query = update.callback_query
    await query.answer()
    data = query.data

    if data == "duration_skip":
        context.user_data['duration'] = None
    else:
        context.user_data['duration'] = data.split('_')[1]

    keyboard = [
        [InlineKeyboardButton("🧒 6+ (6-11 лет)", callback_data="age_6"),
         InlineKeyboardButton("👨 12+ (12-17 лет)", callback_data="age_12")],
        [InlineKeyboardButton("👴 18+ (18+)", callback_data="age_18"),
         InlineKeyboardButton("🎲 Не важно", callback_data="age_skip")],
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    players_text = context.user_data.get('players', 'любое')
    duration_text = context.user_data.get('duration', 'любое')
    await query.edit_message_text(
        f"👥 Игроков: *{players_text}*\n"
        f"⏱️ Время: *{duration_text if duration_text != 'любое' else 'не важно'}*\n\n"
        f"📅 *Какое возрастное ограничение?*",
        reply_markup=reply_markup,
        parse_mode='Markdown'
    )
    return AGE


async def age_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle age selection. Filter games and display results.
    """
    query = update.callback_query
    await query.answer()
    data = query.data

    if data == "age_skip":
        context.user_data['age'] = None
    else:
        context.user_data['age'] = data.split('_')[1]

    players = context.user_data.get('players')
    duration = context.user_data.get('duration')
    age = context.user_data.get('age')

    filtered_games = bot.filter_games(players, duration, age)

    if not filtered_games:
        await query.delete_message()
        await update.effective_chat.send_message(
            "❌ *Не нашлось игр под ваши критерии.*\n\nНажмите /start для нового поиска",
            parse_mode='Markdown'
        )
        return ConversationHandler.END

    context.user_data['filtered_games'] = filtered_games
    context.user_data['current_index'] = 0
    await query.delete_message()
    await show_game(update, context)
    return ConversationHandler.END


async def show_game(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Display current game with navigation buttons.
    """
    filtered_games = context.user_data.get('filtered_games', [])
    current_index = context.user_data.get('current_index', 0)

    if not filtered_games:
        return

    game = filtered_games[current_index]
    total = len(filtered_games)

    keyboard = []
    nav_buttons = []

    if current_index > 0:
        nav_buttons.append(InlineKeyboardButton("◀️ Предыдущая", callback_data="prev_game"))
    if current_index < total - 1:
        nav_buttons.append(InlineKeyboardButton("Следующая ▶️", callback_data="next_game"))

    if nav_buttons:
        keyboard.append(nav_buttons)

    keyboard.append([InlineKeyboardButton("🔄 Новый поиск", callback_data="new_search")])
    reply_markup = InlineKeyboardMarkup(keyboard)

    message_text = bot.format_game_message(game, current_index + 1, total)

    if 'last_message_id' in context.user_data:
        try:
            await context.bot.edit_message_text(
                chat_id=update.effective_chat.id,
                message_id=context.user_data['last_message_id'],
                text=message_text,
                parse_mode='Markdown',
                disable_web_page_preview=True,
                reply_markup=reply_markup
            )
        except:
            msg = await update.effective_chat.send_message(
                message_text,
                parse_mode='Markdown',
                disable_web_page_preview=True,
                reply_markup=reply_markup
            )
            context.user_data['last_message_id'] = msg.message_id
    else:
        if update.callback_query:
            msg = await update.callback_query.message.reply_text(
                message_text,
                parse_mode='Markdown',
                disable_web_page_preview=True,
                reply_markup=reply_markup
            )
        else:
            msg = await update.effective_chat.send_message(
                message_text,
                parse_mode='Markdown',
                disable_web_page_preview=True,
                reply_markup=reply_markup
            )
        context.user_data['last_message_id'] = msg.message_id


async def navigation_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle navigation between games and new search requests.
    """
    query = update.callback_query
    await query.answer()
    action = query.data

    if action == "prev_game":
        context.user_data['current_index'] -= 1
        await show_game(update, context)
    elif action == "next_game":
        context.user_data['current_index'] += 1
        await show_game(update, context)
    elif action == "new_search":
        await query.message.reply_text("/start")


async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle cancel command. Clear user data and end conversation.
    """
    if update.callback_query:
        query = update.callback_query
        await query.answer()
        await query.message.delete()
        await query.message.reply_text("❌ Поиск отменен.\nНажмите /start для нового поиска")
    else:
        await update.message.reply_text("❌ Поиск отменен.\nНажмите /start для нового поиска")
    context.user_data.clear()
    return ConversationHandler.END


async def main():
    """
    Initialize and start the bot application.
    """
    app = Application.builder().token(TOKEN).build()

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
            PLAYERS: [CallbackQueryHandler(players_handler, pattern='^players_')],
            DURATION: [CallbackQueryHandler(duration_handler, pattern='^duration_')],
            AGE: [CallbackQueryHandler(age_handler, pattern='^age_')],
        },
        fallbacks=[
            CommandHandler('start', start),
            CommandHandler('cancel', cancel),
        ],
        allow_reentry=True,
    )

    app.add_handler(conv_handler)
    app.add_handler(CallbackQueryHandler(navigation_handler, pattern='^(prev_game|next_game|new_search)$'))

    print("Bot is ready")

    await app.initialize()
    await app.start()
    await app.updater.start_polling()

    return app


if 'google.colab' in sys.modules:
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(main())
    print("Bot is working in Colab")

    import nest_asyncio
    nest_asyncio.apply()

    await asyncio.Event().wait()
else:
    asyncio.run(main())